name: Push to GCR GitHub Action
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-push-to-gcr:
    name: "Building and pushing images"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/push-to-gcr-github-action@v4.1
        with:
          gcloud_service_key: ${{ secrets.JSON_GCLOUD_SERVICE_ACCOUNT_JSON }}
          registry: gcr.io
          project_id: helix-dev-pancake
          image_name: pancakeswap-ifo-scaler
          image_tag: latest, ${{ github.sha }}
          dockerfile: ./Dockerfile
          context: ./
          target: build